# Generated by Django 3.2.3 on 2021-08-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_code_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
