# Generated by Django 3.2.3 on 2021-08-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_product_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busy_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
