# Generated by Django 3.2.3 on 2021-09-18 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_busy_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='busy_product',
            name='report',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
            preserve_default=False,
        ),
    ]
