# Generated by Django 3.2.3 on 2021-09-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_busy_product_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
